Add : Picturelist 구현
wecode-bootcamp-korea/21-2nd-YourHouseToday-backend pull request #2
Opened 2021-06-23 10:46 UTC by cj4207

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 오늘의집 사진 리스트
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 필터링, 리스트, pagination 기능
<img width="987" alt="스크린샷 2021-06-23 오후 7 44 59" src="https://user-images.githubusercontent.com/76236466/123083999-a200b580-d45b-11eb-87fe-56db683c126e.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-24 03:01 UTC, Kang-kyunghun requested changes

2021-06-24 03:01 UTC, Kang-kyunghun commented on postings/views.py
> +        page          = int(request.GET.get('page', 1))
페이지네이션을 위한 것 같은데 offset과 limit에 대해서 조사해 보시고 적용해 주세요~
즉, page만 받는 것이 아니고, offset과 limit을 프론트에서 모두 받아서 활용해 주세요.

2021-06-24 03:01 UTC, Kang-kyunghun commented on postings/views.py
> +            postings = Posting.objects.all()[offset:limit]
빈 q을 filter에 넣으면 어떻게 동작할까요? 코멘트 남겨주세요.

2021-06-24 03:01 UTC, Kang-kyunghun commented on postings/views.py
> +            postings = Posting.objects.all().order_by(sort)[offset:limit]
정렬 같은 경우 default 값을 지정해 주는 것이 좋습니다~~

2021-06-24 03:01 UTC, Kang-kyunghun commented on postings/views.py
> +            writer = posting.comment_set.filter(posting_id=posting.id)
posting으로부터 역참조를 하고 있습니다. filter가 있을 때랑 없을 때랑 한 번 차이가 있는지 확인해 보고 코멘트에 남겨주세요.

2021-06-24 06:58 UTC, cj4207 commented on postings/views.py
> +            postings = Posting.objects.all()[offset:limit]
빈 q를 넣으면 all()과 같네요.. 1차때 셀로 확인 해봤는데....ㅠㅠ

2021-06-24 07:00 UTC, cj4207 commented on postings/views.py
> +        page          = int(request.GET.get('page', 1))
수정할게요~

2021-06-24 07:01 UTC, cj4207 commented on postings/views.py
> +            postings = Posting.objects.all().order_by(sort)[offset:limit]
등록순으로 default 설정했습니다

2021-06-24 07:01 UTC, cj4207 commented on postings/views.py
> +            writer = posting.comment_set.filter(posting_id=posting.id)
그러네요..굳이 posting.id로 확인을 한꼴이 되었네요...

2021-06-24 07:07 UTC, cj4207 commented on postings/views.py
> +        page          = int(request.GET.get('page', 1))
제가 이해한 부분이 맞는지...요

2021-06-27 06:08 UTC, Kang-kyunghun requested changes

2021-06-27 06:08 UTC, Kang-kyunghun commented on postings/tests.py
> +        user2        = User.objects.create(email='1234@naver.com', nickname='아이언맨', kakao_id = '2', introduction = 'hi wecode', profile_image='https://image.ohou.se/i/bucketplace-v2-development/uploa
User 생성도 아래 Posting 생성처럼 가독성 높게 바꾸면 좋을 것 같아요~

2021-06-27 06:08 UTC, Kang-kyunghun commented on postings/tests.py
> +            image        = 'https://image.ohou.se/i/bucketplace-v2-development/uploads/cards/snapshots/162433488490966976.jpeg?gif=1&w=1536&webp=2',
url 같은 경우 실제 url을 써도 되지만 너무 길어지면 가독성을 떨어뜨리니 url처럼 보이는 string을 써도 무방합니다.

2021-06-27 06:08 UTC, Kang-kyunghun commented on postings/tests.py
> +        })
다음 3가지 테스트를 추가해 주면 좋을 것 같아요.
1. 필터링이 적용된 test
2. oder_by가 적용된 test
3. 페이지 네이션 test

2021-06-28 07:56 UTC, cj4207 commented on postings/tests.py
> +        user2        = User.objects.create(email='1234@naver.com', nickname='아이언맨', kakao_id = '2', introduction = 'hi wecode', profile_image='https://image.ohou.se/i/bucketplace-v2-development/uploa
수정완료했습니다~

2021-06-28 07:56 UTC, cj4207 commented on postings/tests.py
> +            image        = 'https://image.ohou.se/i/bucketplace-v2-development/uploads/cards/snapshots/162433488490966976.jpeg?gif=1&w=1536&webp=2',
수정완료했습니다~

2021-06-28 07:56 UTC, cj4207 commented on postings/tests.py
> +        })
추가 완료 했습니다~

2021-06-28 09:36 UTC, Kang-kyunghun requested changes

2021-06-28 09:36 UTC, Kang-kyunghun commented on postings/views.py
> +        postings = Posting.objects.filter(q).order_by(sort)[offset:offset+limit]
다음 기능이 남아 있어 의무 사항은 아니지만, 기회가 된다면 해당 코드에 select_related와 prefetch_related을 추가해서 db로 보내는 쿼리를 줄여보면 좋을 것 같아요~~

2021-06-28 09:36 UTC, Kang-kyunghun commented on postings/views.py
> +        if not max_size%10: #front에서 평수 사이즈를 0-10, 11-20, 21-30으로 받아오기 때문에 해결 로직
주석은 속한 그룹에 따라 남기는 방식이 다양하지만, 위코드에서는 공유 코드에는 주석을 달지 않는 것을 기본 원칙으로 하고 있습니다. 해당 주석은 제거해 주세요.

2021-06-29 04:34 UTC, cj4207 commented on postings/views.py
> +        postings = Posting.objects.filter(q).order_by(sort)[offset:offset+limit]
네 기회가 된다면 적용해보겠습니다!!

2021-06-29 04:35 UTC, cj4207 commented on postings/views.py
> +        if not max_size%10: #front에서 평수 사이즈를 0-10, 11-20, 21-30으로 받아오기 때문에 해결 로직
주석제거했습니다!

2021-06-29 05:18 UTC, Kang-kyunghun requested changes

2021-06-29 05:18 UTC, Kang-kyunghun commented on db_uploader.py
> +import os
업로드 파일 제거해 주세요.

2021-06-29 05:51 UTC, cj4207 commented on db_uploader.py
> +import os
넵 확인했습니다

2021-06-29 08:11 UTC, Kang-kyunghun commented
LGTM~~!! 👍

2021-06-29 08:11 UTC, merged