Add:소셜로그인 1.1
wecode-bootcamp-korea/21-2nd-YourHouseToday-backend pull request #3
Opened 2021-06-24 05:02 UTC by geekanne

Modify: 소셜 로그인 1.2 로직 구현 완료

소셜 로그인 1.3 불필요한 로직 정리

Modify: 소셜 로그인 1.4 응답 데이터에 유저 정보 추가

Modify: 소셜 로그인 1.5 print 삭제

Modify: 소셜 로그인 1.7 불필요한 파일 삭제

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 소셜 로그인(로그인/회원가입) 구현
- 토큰 인증 데코레이터 구현
		 
## 수정 사항들 자세한 내용
- (첫번째 패치) 소셜 로그인 토큰으로 유저 정보 유청 >> 받아온 유저 정보가 이미 있는 경우, 토큰 발행하여 리턴 >> 신규 회원인 경우, 유저 정보 리턴하여 추가 정보 입력할 수 있도록 함 >> (두번째 패치) 추가 정보 받아온 후, DB에 저장 후 토큰 발행하여 리턴
- 
## 기타 질문 및 특이 사항
- 카카오에서 받아온 유저의 id를 프런트로 넘겨주어도 괜찮나요?
- 
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-24 06:29 UTC, geekanne commented
리뷰 수정완료하였습니다.

- 액세스 토큰의 존재여부를 판단하는 불필요한 if문 제거
- 기존 회원인지 판단 여부를 if 문으로 분리

2021-06-24 06:36 UTC, Kang-kyunghun requested changes

2021-06-24 06:36 UTC, Kang-kyunghun commented on users/views.py
> +            if access_token == None:
```suggestion
            if access_token is None:
```

2021-06-24 06:36 UTC, Kang-kyunghun commented on users/views.py
> +            user_info = json.loads(response.content)
requests 라이브러리에 response의 body가 json일 때 dictionary로 변환해 주는 method가 있습니다. 찾아보고 적용해 보세요.

2021-06-24 06:41 UTC, geekanne commented on users/views.py
> +            if access_token == None:
수정 완료하였습니다!

2021-06-24 06:41 UTC, geekanne commented on users/views.py
> +            user_info = json.loads(response.content)
수정완료하였습니다!

2021-06-26 18:48 UTC, geekanne commented
1. UNIT TEST 추가
- 로그인/회원가입/닉네임중복체크/인증 데코레이터에 대한 15개 유닛 테스트

2. 리뷰 사항 반영
-삼항 연산자 가독성 좋게 변경

3. 인증 데코레이터에 비회원 로직 추가

4. 회원정보 조회 View 추가

1. 인증데코레이터를 무조건 붙여야 하지만, 회원/비회원이 나뉘는 경우가 있어,
인증데코레이터에 회원/비회원 경우의 수를 나눴는데 이렇게 구현해도 괜찮을까요?
ex) 게시글 페이지에서 회원인 경우에만 '찜하기' 버튼이 나타남

2. 유닛테스트에서, 테스트가 불가능한 경우들은 제외해도 괜찮을까요?
ex) 카카오 로그인 API를 이용하는 경우, 카카오와의 통신과 관련된 에러들
ex) JWT 디코딩 에러의 경우, JWT 생성시 에러가 날 수 있는 경우가 SECTRET KEY와 ALGORITHM에 문제가 생겼을 경우 뿐인데,
이 두 경우에 대해서는 유닛테스트로 테스트가 불가능

3. 유닛테스트 중, 대다수가 데이터 생성이 필요 없고, 일부만 필요해서(15개 테스트 중 3개만),
def setUp/tearDown을 안 쓰고, 필요한 경우에만 해당 테스트 내에서 데이터를 생성하는 게 더 효율적이지 않을까 싶었는데,
이렇게 구현해도 괜찮을까요?

4. 닉네임에서 추천 닉네임을 생성하는 로직이 if/while이 3번 중첩되어 있는데,
아무리 봐도 논리적으로 불가피해 보여서ㅠㅠ 이렇게 작성해도 괜찮을까요?

5. 인증 데코레이터의 경우, 회원정보 조회 View를 통해 테스트 했는데, 이렇게 구현해도 괜찮을까요?

2021-06-27 06:42 UTC, Kang-kyunghun requested changes

2021-06-27 06:42 UTC, Kang-kyunghun commented on users/views.py
> +
불필요한 공백 제거해 주세요.

2021-06-27 06:42 UTC, Kang-kyunghun commented on users/views.py
> +
```suggestion
            profile_image_url = profile.get('profile_image_url', None)
```

2021-06-27 06:42 UTC, Kang-kyunghun commented on users/views.py
> +            if User.objects.filter(nickname=nickname).exists():
중복 체크에 대한 개인적인 생각 몇 가지 남겨 볼게요.
1. 현재 구조가 if 안에 while에 또 if가 들어가서 그런지 가독성 및 성능에도 약간의 불안감이 있네요.
2. 특히 while을 끝내는 조건이 우연히 같은 닉네임이 안 걸릴 때까지 (1000번 돌리는)건데 비효율적인 것 같아요.
3. 뒤에 붙이는 숫자를 등록된 유저의 id 중 가장 큰 값에 1을 더해 주는 것은 어떨까 싶어요

2021-06-27 06:42 UTC, Kang-kyunghun commented on users/tests.py
> +        )
이러한 데이터 생성을 setup에서 하셔야 합니다. 그리고 teardown으로 정리 하고요

2021-06-27 06:42 UTC, Kang-kyunghun commented on users/tests.py
> +        )
여기도 setup에서 해야할 작업입니다.

2021-06-27 06:51 UTC, Kang-kyunghun commented
1. 인증데코레이터를 무조건 붙여야 하지만, 회원/비회원이 나뉘는 경우가 있어,

해당 질문은 코드를 보면서 같이 이야기 해봐야 할 것 같아요.

2. 유닛테스트에서, 테스트가 불가능한 경우들은 제외해도 괜찮을까요?
카카오와 통신 에러면 카카오와 통신이 안 되었을 때를 이야기 하는 것인가요? 이럴 경우를 대비해서 requests 요청에 제한 시간을 걸어야 합니다.
JWT 같은 경우는 굳이 테스트 안 해도 될 것 같아요.


3. 유닛테스트 중, 대다수가 데이터 생성이 필요 없고, 일부만 필요해서(15개 테스트 중 3개만),

테스트 진행 시 데이터가 안 사용 되는 경우가 거의 없을 거라고 생각 됩니다. 
일다 리뷰 진행해 보니 사용 했어야 하는 부분들이 있었습니다. 한 번더 확인해 주세요.

4. 닉네임에서 추천 닉네임을 생성하는 로직이 if/while이 3번 중첩되어 있는데,
아무리 봐도 논리적으로 불가피해 보여서ㅠㅠ 이렇게 작성해도 괜찮을까요?

코드에 리뷰 남겨 드렸어요~

5. 인증 데코레이터의 경우, 회원정보 조회 View를 통해 테스트 했는데, 이렇게 구현해도 괜찮을까요?

괜찮을 것 같아요~

2021-06-28 02:41 UTC, Kang-kyunghun commented
정연님 mock data도 너무 많아 질 경우 관리하기 위해서 class로 관리 한다고 합니다.
아니면, django에 Factory 라이브러리도 많이 사용한다고 하니 찾아 보면 도움 될 것 같아요

2021-06-28 16:28 UTC, geekanne commented
> 정연님 mock data도 너무 많아 질 경우 관리하기 위해서 class로 관리 한다고 합니다.
> 아니면, django에 Factory 라이브러리도 많이 사용한다고 하니 찾아 보면 도움 될 것 같아요

앗 감사합니다! 더 찾아보겠습니다!!

2021-06-28 16:31 UTC, geekanne commented
1. 인증 데코레이터 구분
- 회원 전용 인증 데코레이터
- 회원/비회원 구분용 인증 데코레이터

2. 데코레이터에 대한 유닛테스트 추가
- 데코레이터 유닛 테스트를 안해도 되는 줄 모르고 모두 구현하였습니다.ㅠㅠ

3. 유닛테스트의 데이터 셋업을 분리
- setUpTestData 함수 사용하여, 데이터 셋업과 / 로직 테스트를 분리

4. 닉네임 중복 체크 - 추천 닉네임 로직을 리뷰 반영하여 변경
- 등록된 유저의 id 중 가장 큰 값에 1을 더해 주는 로직으로 변경

2021-06-29 05:21 UTC, Kang-kyunghun commented
1. test.py가 누락 되어 있는데 확인 부탁드릴게요.
2. 리베이스 후 커밋 메시지는 해당 PR이 어떤 기능을 하는지 설명을 적어 주면 좋습니다. 지금은 그 동안의 수정 사항들을 커밋 메시지로 남겼는데, 굳이 안 남기는 것이 좋을 것 같습니다.

2021-06-29 05:24 UTC, Kang-kyunghun requested changes

2021-06-29 05:24 UTC, Kang-kyunghun commented on users/views.py
> +
공백이 자꾸 생기네여~~

2021-06-29 13:16 UTC, Kang-kyunghun commented
고생 많았어요~ 👍

2021-06-29 13:16 UTC, merged