ADD:posting 로직구성 및 좋아요 로직구성
wecode-bootcamp-korea/21-2nd-YourHouseToday-backend pull request #4
Opened 2021-06-25 08:51 UTC by JangDongGuk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 상세페이지 로직 구현
- 좋아요 로직 구현
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-27 06:02 UTC, Kang-kyunghun requested changes

2021-06-27 06:02 UTC, Kang-kyunghun commented on db_uploader.py
> +import os
해당 파일 제거하고 gitignore에 추가하세요.

2021-06-27 06:02 UTC, Kang-kyunghun commented on postings/views.py
> +        delete_posting = Like.objects.filter(posting_id = data['posting_id'], user_id = data['user_id'])
user_id는 데코레이터로 받은 user 정보를 활용해 주세요.

2021-06-27 06:02 UTC, Kang-kyunghun commented on postings/views.py
> +        return JsonResponse({'message':'CREATE_LIKE'}, status=201)
해당 view는 posting과 관련된 view입니다. 그래서 해당 view에서 post method의 역할은 posting을 등록하는 기능이 더 어울릴 것 같아요. 좋아요 기능은 따로 view을 만들어 주세요.

2021-06-27 06:02 UTC, Kang-kyunghun commented on postings/views.py
> +    @login_decorator
posting 상세 페이지는 로그인 하지 않은 유저도 볼 수 있을 것 같은데 로그인 데코레이터를 붙인 이유가 있나요? 있다면 코멘트로 남겨주세요.

2021-06-28 06:53 UTC, JangDongGuk commented on db_uploader.py
> +import os
네 수정했습니다.!

2021-06-28 06:53 UTC, JangDongGuk commented on postings/views.py
> +        delete_posting = Like.objects.filter(posting_id = data['posting_id'], user_id = data['user_id'])
네 수정했습니다.!

2021-06-28 06:53 UTC, JangDongGuk commented on postings/views.py
> +        return JsonResponse({'message':'CREATE_LIKE'}, status=201)
네 수정했습니다.!

2021-06-28 06:54 UTC, JangDongGuk commented on postings/views.py
> +    @login_decorator
따로 수정 및 삭제 기능이 없기에 데코레이터 빼는 걸로 수정했습니다.

2021-06-28 09:40 UTC, Kang-kyunghun commented
지금 해당 pr과 관련 없는 코드들이 많이 올라 온 것 같아요 확인 부탁드릴게요~
업로드 파일도 또 올라 왔습니다.

2021-06-29 05:26 UTC, Kang-kyunghun commented
git 작업 중에 문제가 생긴 것으로 보입니다. 제가 직접 가서 확인 해야 할 것 같아요

2021-06-29 08:13 UTC, Kang-kyunghun commented
users app의 urls.py 한 번 확인해 주세요. 아무것도 없네요

2021-06-30 01:34 UTC, Kang-kyunghun commented
고생 하셨습니다~~ 👍

2021-06-30 01:34 UTC, merged